### ISSUE TITLE
owner absent sur project

### ISSUE THREAD

**Issue by jcheron** [dixplo/projet_boards_nathan#2]
https://github.com/dixplo/projet_boards_nathan/blob/ed5ac7842889352e00efa27c2e2df148760b9353/app/routes/projects/new.js#L18

le `developer` qui est passé, c'est une liste de developers !

```javascript
model.owner.save().then(()=>{this.transitionTo('projects');});
```

**Comment by nathanpriou** [comment]
Ca ne change rien :/
le owner s'affiche toujours comme ça : <(unknown):ember207>
Et ne s'enregistre pas de la collection developers

**Comment by jcheron** [comment]
https://github.com/dixplo/projet_boards_nathan/blob/ed5ac7842889352e00efa27c2e2df148760b9353/app/templates/projects/index.hbs#L22

Le `project.owner` c'est un objet !
Comment voulez-vous l'afficher comme ça sans lui ajouter un `toString` ?
ou alors en faisant:
```
<td>{{projects.owner.identity}}</td>
```
